### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Taknax** [doch2/SmartMovingReboot#1]
Amazing you did it. 
Their is a library named obfuscate by mrcrayfish. Its combine PlayerAPI, SmartRender and RenderPlayer in one mod and its compatible with most mods out their. The other bonus is, its easier to update SM to newer version of minecraft. Mods from mrcrayfish and some other mods (AdvancedRocketry) almost use obfuscate. It would higher the mod compatiblity and obfuscate is pretty famous. Im really glad you updated this and i want to help to improve.

**Comment by doch2** [comment]
I am know that there is a problem with the current condition. Changing the Minecraft code to use the mode is a problem, and it should be developed again using obfuscate library as soon as possible. But it will be difficult right now because I don't have time to do such redevelopment. Please understand, and if you have the ability to develop, please contribute to this project.

**Comment by Taknax** [comment]
Ofc no problem. Its only the way for the future maybe. Im glad you revived and i can use. :)
I try to get knowledge bout this. If you have any advise or idea you can tell me.
